title: "Hi! I'm Andy Vu"
description: "A Master's Mechanical Engineering Student at CMU"
theme: jekyll-theme-minimal

navbar-links:
  - text: "Home"
    url: "/"
  - text: "Projects"
    url: "/projects/"
  - text: "About"
    url: "/about/"

include:
  - assets
  - projects
  - research
