title: "Hi! I'm Andy Vu"
description: "A Master's Mechanical Engineering Student at CMU"
theme: jekyll-theme-minimal

navbar-links:
  - text: "Home"
    url: "/"
  - text: "About"
    url: "/about/"
  - text: "Experience"
    url: "/experience/"
  - text: "Projects"
    url: "/projects/"
  - text: "Research"
    url: "/research/"

include:
  - assets
  - projects
  - research
  
plugins:
     - jekyll-optional-front-matter
