title: "Hi! I'm Andy Vu"
description: "A Master's Mechanical Engineering Student at CMU"
theme: jekyll-theme-minimal

navbar-links:
  Home: "/"
  About: "/about"
  Experience: "/experience"
  Projects: "/projects"
  Research: "/research"

include:
  - assets
  - projects
  - research
